### ISSUE TITLE
UFO3 kerning: group in groups.plist without public.kern[12]. prefix used as kerning class

### ISSUE THREAD

**Issue by madig** [googlei18n/ufo2ft#244] opened 2018-04-11 09:46 UTC
We are working on a UFO3 font that has the following properties; _note that the kerned glyph carries the same names  as the group_:

UFO group.plist:
```
[...]
		<key>dNa4.half</key>
		<array>
			[...]
		</array>
[...]
```
UFO kerning.plist:
```
[...]
		<key>dNa4.half</key>
		<dict>
			<key>...</key>
			<integer>-80</integer>
		</dict>
[...]
```
In the generated feature file, we get
```
enum pos @dNa4.half ... -80;
```
Instead of
```
pos dNa4.half ... -80;
```
The UFO2 spec allows it, the UFO3 spec doesn't. So in this case, the group from group.plist should be ignored. Looking into it.

**Comment by anthrotype** [comment] 2018-04-11 10:15
could you please check if that occurs with this wip branch?
https://github.com/googlei18n/ufo2ft/tree/feature-writer-wip

I still need to finish that (cleanup, add tests), got busy with other stuff

**Comment by anthrotype** [comment] 2018-04-11 10:16
I think this issue is a duplicate of https://github.com/googlei18n/ufo2ft/issues/204

**Comment by madig** [comment] 2018-04-11 10:36
Oh. Damn, and I wrote a fix 😁 Will try.

**Comment by madig** [comment] 2018-04-11 10:41
Can't test:
```
Traceback (most recent call last):
  File "C:\...\venv\Scripts\fontmake-script.py", line 11, in <module>
    load_entry_point('fontmake==1.5.0.dev0', 'console_scripts', 'fontmake')()
  File "C:\...\venv\lib\site-packages\fontmake\__main__.py", line 226, in main
    ufo_paths, is_instance=args.pop('masters_as_instances'), **args)
  File "C:\...\venv\lib\site-packages\fontmake\font_project.py", line 525, in run_from_ufos
    **kwargs)
  File "C:\...\venv\lib\site-packages\fontmake\font_project.py", line 224, in build_ttfs
    self.save_otfs(ufos, ttf=True, **kwargs)
  File "C:\...\venv\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "C:\...\venv\lib\site-packages\fontmake\font_project.py", line 321, in save_otfs
    font = compileTTF(ufo, convertCubics=False, **compiler_options)
TypeError: compileTTF() got an unexpected keyword argument 'kernWriterClass'
```
fontmake git master...

**Comment by anthrotype** [comment] 2018-04-11 10:55
yep, that's why is marked wip.
just call `ufo2ft.compileTTF` function yourself with a `defcon.Font`

**Comment by madig** [comment] 2018-04-11 11:09
Okay, your branch seems to solve it.

**Comment by anthrotype** [comment] 2018-06-12 11:44
fixed in master, release will come later today

**Closed by anthrotype** 2018-06-12 11:44 UTC
