### ISSUE TITLE
`kernFeatureWriter.py` does not inline feature file `include` statements before parsing features

### ISSUE THREAD

**Issue by jmsole** [googlei18n/ufo2ft#190] opened 2017-12-13 11:45 UTC
On projects where you want to have a global `family.fea` file and use `include(../family.fea)` to refer to it on each of the UFO's to avoid unnecessary duplication, it seems like `kernFeatureWriter.py` does not inline the `include` statement and so it doesn't take into account RTL scripts in the font since it can't find any `languagesystem` tags on each individual UFO's feature file.

The end result is it ends up with no RTL kerning and all the kerning is put into a single lookup, when it should be split into two lookups with different directions.

**Comment by anthrotype** [comment] 2017-12-13 14:08
yeah.. thanks Jose.
closing as duplicate of https://github.com/googlei18n/ufo2ft/issues/112

**Closed by anthrotype** 2017-12-13 14:08 UTC

**Comment by jmsole** [comment] 2017-12-13 14:19
Ahhh, should have read that one more closely. Thanks!
